app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

routes/web.php
<?php

use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;



//use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

 Route::get('/exporttest', function(){
    $photos = \App\Photo::All();

    foreach($photos as $photo){
        if(!Storage::exists('photos/'.$photo->filepath)){
            echo $photo->filepath . "<br>";
        }
       
    }

 });




 
// preview application report mailable
Route::get('/mailable', function () {

    return new App\Mail\ApplicationReport(Auth::user());
});





Route::get('/labeltest', function() {

    $users = \App\User::All();

    $sections =[];

    foreach ($users as $user) {
        //$user = \App\User::find(59);

        $prints = $user->prints()
        ->with('section')->get();

       
        //$sections[$user->id] = [];
        $entryNo =0;
        $lastSectionId = null;

        

        foreach ($prints as $print) {

            if($print->section_id != $lastSectionId){
                $entryNo =0;
            }

            if ($entryNo++ != $print->section_entry_number){
                $sections[$user->email][$print->section_id][$entryNo - 1] = $print->section_entry_number;
            }

            
            $lastSectionId = $print->section_id;

        }

    }

    
    
    dd($sections);


    // $pdf = PDF::loadView('entries.labels', compact('user','prints'));

    //     // Save pdf to storage
    //    Storage::disk('public')->put('labels/labels_' . $user->id.'.pdf',$pdf->output());


    //     return $pdf->stream('labels.pdf');


    //dd ($prints);
    
});

Route::get('/', 'WelcomeController@index');

// Laravels std auth routes
Auth::routes(); // plus a convenience get version for logout
Route::get('logout', 'Auth\LoginController@logout');

// User registration
Route::get('registered', 'Auth\RegisterController@registered')->name('registered');
Route::get('register/confirm/{token}', 'Auth\RegisterController@confirmEmail');

// App admin routes
Route::prefix('admin')->middleware(['auth', 'can:admin'])->group(function () {
    Route::get('dashboard', 'AdminController@index')->name('admin.dashboard');

    Route::get('settings', 'SettingsController@index')->name('admin.settings');
    Route::post('settings', 'SettingsController@update')->name('admin.settings.update');

    Route::get('credentials', 'AdminCredentialsController@index')->name('admin.credentials.form');
    Route::post('credentials', 'AdminCredentialsController@update')->name('admin.credentials.update');

    Route::get('sections', 'AdminCategoryController@index')->name('admin.category.form');
    Route::post('sections', 'AdminCategoryController@update')->name('admin.category.update');

    Route::get('clubs', 'ClubsController@index')->name('admin.clubs');
    Route::post('clubs', 'ClubsController@update')->name('admin.clubs.update');
// List, Edit, Update applications
    Route::get('applications', 'AdminApplicationController@index')->name('admin.applications');
    Route::get('application/{application}/edit', 'AdminApplicationController@edit')->name('admin.application.edit');
    Route::post('application/{application}', 'AdminApplicationController@update')->name('admin.application.update');
    Route::get('application/{application}/verifyemail', 'AdminApplicationController@verifyEmail')->name('admin.application.verifyemail');

// Messaging routes
    Route::get('messaging', 'AdminMessagingController@index')->name('admin.messaging');
    Route::post('messaging/message_list', 'AdminMessagingController@messageList')->name('admin.message_list');
    Route::post('messaging/message_all', 'AdminMessagingController@messageAll')->name('admin.message_all');
    Route::post('messaging/message_results', 'AdminMessagingController@messageResults')->name('admin.message_results');

    Route::get('application/exportcsv', 'AdminExportController@exportcsv')->name('admin.application.exportcsv');

    Route::get('export/photos', 'ExportPhotosController@export_dashboard')->name('admin.export.photos');
    Route::post('export/photos/{id}', 'ExportPhotosController@export');

    Route::get('reset', 'AdminResetController@reset')->name('admin.master.reset');

    Route::post('acceptances', 'AdminAcceptanceController@sendCertificates')->name('admin.acceptances');

    Route::post('background', 'AdminAcceptanceController@background')->name('admin.acceptance.background');

    // List  & edit/delete logins
    Route::get('/accounts', 'AccountEditController@index')->name('admin.accounts.list');
    Route::get('/account/{id}', 'AccountEditController@edit')->name('admin.account.edit');
    Route::post('account/{id}', 'AccountEditController@update')->name('admin.account.update');

    Route::get('/entryTest', function(){
        return view('emails.entry_report_test');
        
    });

    
});

// image provider for certificates
Route::get('acceptance/photo/{filepath}','AdminAcceptanceController@getAcceptancePhoto')->name('admin.acceptance.photo');


Route::middleware(['auth', 'can:enter'])->group(function () {

    Route::get('/labelpdf', function(){

    
        
        $user = Auth::guard('web')->user();
       
        // Get list of user PRINTS ie User Photos where category_id =2

        $prints = $user->prints()->with('section')->get();
       
        

       // dd($user->prints->count());
       
       

        // return view('entries.labels2',compact('user','prints'));

       $pdf = PDF::loadView('entries.labels', compact('user','prints'));

        // Save pdf to storage
        // Storage::disk('public')->put('labels/labels_' . $user->id.'.pdf',$pdf->output());


        return $pdf->stream('labels.pdf');
    


    });


    // Display the first application form
    Route::get('/home', 'HomeController@index')->name('home');


// Show and Process the  application form
    Route::get('/application', 'ApplicationController@showRegistrationForm')->name('show_application_form');
    Route::post('/application', 'ApplicationController@processRegistrationForm')->name('process_application_form');

// Show image entry upload form - ajax uplaod handler
    Route::get('/editentries', 'EntriesEditController@index')->name('edit_entries');  
    Route::get('/entries', 'EntriesController@index')->name('entries_upload_form');
   

    // The following were added to the api routes file api.php
    // Route::post('/process', 'EntriesController@process')->name('process');
    // Route::post('/upload', 'EntriesController@uploader')->name('uploader');
    // Route::post('/submit', 'EntriesController@submit');

// Checkout
    Route::get('/checkout', 'CheckoutController@index')->name('checkout');
    Route::get('/checkout/using/{method}', 'CheckoutController@using')->name('checkout.using');
// Payment request
    Route::get('/checkout/final/{method}', 'CheckoutController@final')->name('checkout.final');

    Route::get('/labels/{user}','PdfController@index')->name('labelmaker');;

});

Route::prefix('paypal')->group(function () {
    Route::post('ipn', 'PaypalController@ipn'); // needs CSRF middleware disabled

    Route::get('success', 'PaypalController@success');
    Route::get('cancel', 'PaypalController@cancel');
});

app/Application.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'salutation',
        'firstname',
        'lastname',
        'honours',
        'address1',
        'address2',
        'city',
        'state',
        'postcode',
        'country',
        'phone',
        'vaps_affiliated',
        'aps_member',
        'aps_membership_number',
        'club_name',
        'club_nomination',
        'confirm_terms',
        'where_hear',

        // Entry form
        'number_of_entries',
        'number_of_sections',
        'entries_cost',
        'return_postage',
        'return_post_option',
        'return_group',
        'submitted',
        'payment_method',

        'mc_gross',
        'mc_gross_1',
        'mc_gross_2',
        'mc_fee',
        'txn_id',
        'payment_date',
    ];

    protected $casts = [
        'entries_cost' => 'float',
        'number_of_entries' => 'integer',
        'mc_gross' => 'float',
        'mc_gross_1' => 'float',
        'mc_gross_2' => 'float',
        'mc_fee' => 'float',
    ];

    /**
     * Get the user's full name.
     *
     * @return string
     */
    public function getFullnameAttribute()
    {
        return "{$this->salutation} {$this->firstname} {$this->lastname}";
    }
    public function getShortnameAttribute()
    {
        return "{$this->firstname} {$this->lastname}";
    }

    public function getCompletedAttribute()
    {
        return $this->confirm_terms == 'checked';
    }

    public function getPaidAttribute()
    {
        return $this->txn_id !== null;
    }

    public function delete()
    {
        // delete all related photos 
        $this->photos()->delete();
        
        // delete the application
        return parent::delete();
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function photos()
    {
        return $this->hasMany('App\Photo', 'user_id', 'user_id');
    }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        {{-- dump($application) --}}
        {{-- dump($application->completed) --}}
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Entrant Dashboard</h3>
                    @if($application->completed)
                        {{ $application->fullname }}
                    @else
                        {{ Auth::user()->email }}
                    @endif

                </div>

                <div class="panel-body dashboard">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <p>The section below lists the current status of your entry</p>

                    <div class="row" >
                        <div class="col-sm-4">Step 1<br />
                            @if(!$application->completed )
                             <a href="{{ route('show_application_form') }}" >Complete the Application Form</a>
                             @else
                             Complete the Application Form<br/>
                            
                            @endif


                        </div>
                        <div class="col-sm-6">
                            <p>
                                @if( $application->completed )
                                    Application Form has been completed<br />
                                    <!--<a href="{{ route('show_application_form') }}" >Edit Application Form</a>-->
                                @else
                                    Application Form has NOT been completed
                                @endif
                            </p>
                        </div>
                        <div class="col-sm-2"><span class="icon glyphicon {{ $application->completed ? 'glyphicon-ok' : 'glyphicon-remove' }}"></span></div>
                    </div>

                    <div class="row" >
                        <div class="col-sm-4">Step 2:<br />
                            @if($application->completed && !$application->submitted)
                            <a href="{{ route('entries_upload_form') }}">Complete the Entry Form</a>
                            
                            @else
                            Complete the Entry Form
                            
                            @endif

                        </div>
                        <div class="col-sm-6">
                            <p>


                               @if($application->completed)
                                    @if($application->submitted )
                                        Entry form has been completed<br />
                                        
                                            <a href="{{ route('entries_upload_form') }}">View entries</a><br>
                                            <a href="{{ route('edit_entries') }}" >Edit  entries</a>
                                            @if($application->user->prints->count())
                                                <br>
                                                <a href="{{ url('labelpdf') }}" >Print entry labels pdf</a>
                                            @endif
                                    
                                    @else
                                        Entry Form has NOT been completed
                                    @endif

                                @else
                                    Please complete Step 1 before Step 2<br />
                                @endif
                            </p>
                        </div>
                        <div class="col-sm-2"><span class="icon glyphicon {{ $application->submitted ? 'glyphicon-ok' : 'glyphicon-remove' }}"></span></div>
                    </div>

                    <div class="row">
                        <div class="col-sm-4">Step 3<br />
                            @if($application->submitted && ! $application->paid )
                                <a href="{{ route('checkout') }}">Pay entry fee</a>
                            @elseif($application->paid)
                                Pay entry fee (Entry fee has been paid)
                            @else
                                Pay the entry fee
                            @endif



                        </div>
                        <div class="col-sm-6">
                            <div>
                                @if($application->paid)
                                    <table>
                                        <tr>
                                            <td>Payment Method:&nbsp;</td>
                                            <td>{{ ucWords(strtolower($application->payment_method)) }}</td>
                                        </tr>
                                        <tr>
                                            <td>Payment date:&nbsp;</td>
                                            <td>{{ $application->payment_date }}</td>
                                        </tr>
                                        <tr>
                                            <td>Payment amount:&nbsp;</td>
                                            <td>${{ number_format($application->mc_gross,2) }}</td>
                                        </tr>

                                    </table>

                                   
                                @else
                                    @if($application->submitted)
                                        <p>The fee for your current entries will be ${{ number_format($application->entries_cost + $application->return_postage,2) }}</p>
                                        @if($application->payment_method == 'direct_debit')
                                        <p>You have indicated you will be paying the entry fee by <strong>Direct Debit</strong>.</p>

                                        @endif

                                        @if($application->payment_method == 'paypal')
                                        <p>You have indicated you will be paying the entry fee via <strong>Paypal</strong>. </p>
                                        @endif

                                        @if($application->payment_method)
                                        <p>Once your payment has been received your entry will be updated and the payment details will be displayed here.</p>

                                        @endif
                                    @else
                                       <p>Complete Step 1 and Step 2 before making payment</p>
                                    @endif
                                @endif

                            </div>
                        </div>
                        <div class="col-sm-2"><span class="icon glyphicon {{ $application->paid ? 'glyphicon-ok' : 'glyphicon-remove' }}"></span></div>
                    </div>



                </div>
            </div>
        </div>
    </div>
</div>
@endsection